### ISSUE TITLE
BorshDeserialize shouldn't require `Copy`

### ISSUE THREAD

**Issue by austinabell** [near/borsh-rs#103]
Is there any reason the `Copy` bound for array de serialization can be downgraded to `Clone`? It's unfortunate in general why this bound exists, seems like it's just for bytes deserialization.

This should just work:

```rust
#[derive(BorshDeserialize, BorshSerialize)]
pub struct MyStruct {
    test: [String; 2],
}
```

and ideally this too:

```rust
#[derive(BorshDeserialize, BorshSerialize)]
struct Inner;

#[derive(BorshDeserialize, BorshSerialize)]
pub struct MyStruct {
    test: [Inner; 2],
}
```

**Comment by frol** [comment]
I don't think there was a particular reason. It might have been some Rust limitation defining boundaries, but other than that, I don't know what holds us from fixing it.

**Comment by lovrozitnik** [comment]
Please fix this!

**Comment by austinabell** [comment]
Looked into this a bit. Very hard to make a simple fix now that there are const generics for the array impls and they don't play nice with `MaybeUninit` arrays (trying to remove the clone bound altogether). Also noticing that there is a very unnecessary `Default` bound on the array to deserialize. This is only used to write default values to the array before writing over it.

Also not straightforward to initialize default array with the generic type. Seems like the only way to solve this is with some possibly janky unsafe code.

Doesn't really seem worth it to do a hacky solution to just switch `Copy` to `Clone` since it comes with some other unideal side effects. Opening PR soon
