### ISSUE TITLE
Add MSRV check to CI

### ISSUE THREAD

**Issue by austinabell** [near/borsh-rs#106]
Currently, changes can bump the MSRV without noticing. Would be good to have this documented and stable for #51.

Noticed from #104 bumping MSRV without any failing CI

**Comment by matklad** [comment]
FWIW, I’ve recently written down my current thoughts on MSRV here: https://github.com/matklad/once_cell/issues/201

**Comment by austinabell** [comment]
Hmm, I completely understand the viewpoint, and maybe we make no guarantees about bumping msrv during minor/patch versions, but is it not still beneficial to have this msrv controlled and visible?

Feel free to close, I don't have an actual opinion on this

**Comment by matklad** [comment]
Crates should document their MSRV policy, and, if the policy is different from "latest stable" it should be tested on CI. 

I am not entirely sure what's the right MSRV policy for borsh, the following makes sense to me:

* MSRV is not breaking
* MSRV is six months at least
* explicit non-support for debian stable and such
* newer compilers can be used if required by a feature (cosnt-generics) or via feacher-checking in build.rs (eg, via rustc-version or autocfg crates). 

If we have abundance of resources, 2 year MSRV would also make sense to me

If we are very short on resources, I think declaring "latest stable" won't be catastrophic either.
