### ISSUE TITLE
Cloned enum struct variant fields are reported as unused

### ISSUE THREAD

**Issue by miraclx** [near/borsh-rs#111]
Take this example:

```rust
use near_sdk::borsh::{self, BorshSchema};

#[derive(BorshSchema)]
pub enum A {
    B {
        c: (),
    },
}
```

Rust reports:

```console
warning: field `c` is never read
  --> src/lib.rs:12:9
   |
3  | #[derive(BorshSchema)]
   |          ----------- field in this struct
...
6  |         c: (),
   |         ^
   |
   = note: `#[warn(dead_code)]` on by default
```

Removing the derive, the warning goes away.

This is somewhat related to https://github.com/near/borsh-rs/issues/110, where `BorshSchema` clones the `A::B` path into a struct `AB`, for which it then derives `BorshSchema`.

```rust
#[derive(BorshSchema)]
struct AB {
    c: (),
}
```

Looking at this, it's easier to see why rust reports an unread variable.

**Comment by dj8yfo** [comment]
taking this issue
