### ISSUE TITLE
FR: Provide a way to borrow data from a slice.

### ISSUE THREAD

**Issue by mina86** [near/borsh-rs#122]
For example,

```rust
let serialised: &[u8] = todo!();
let slice = <&[u8]>::try_from_slice(serialised)?;
```

```rust
#[derive(BorshDeserialise)]
enum Record<'a> {
    JustKey(&'a [u8]),
    KeyAndValue(&'a [u8], &'a [u8]),
}

match Record::try_from_slice(serialised) {
    Record::JustKey(key) => todo!(),
    Record::KeyAndValue(key, value) => todo!(),
}
```

**Comment by frol** [comment]
This is definitely a great feature to have! Yet, I believe it is not going to be on Pagoda's plate any time soon, but I am happy to review a PR if someone will implement this feature.

**Comment by dj8yfo** [comment]
this is a  example of a variant of how this could be done. https://github.com/dj8yfo/borrow_deserialize
It's not minimal enough to fit into a small gist.

It might be better to create a separate trait `BorshBorrowDeserialize<'de>` for this and not attempt to mix everything in one trait 
https://github.com/dj8yfo/borrow_deserialize/blob/master/src/deserialize_trait.rs#L7

**Comment by frol** [comment]
Well, adding a method and a lifetime to the existing public trait is going to be a major breaking change. I don't have the capacity right now to assess how cumbersome would a separate trait path be. I think overall, we may keep this issue in a backlog for now and think about it in the background while we are addressing other papercuts.
