### ISSUE TITLE
Enum discriminant is not serialized when specified

### ISSUE THREAD

**Issue by encody** [near/borsh-rs#137]
The [specification](https://github.com/near/borsh#specification) says that for serializing enums, the pseudocode procedure is as follows:

> Suppose X is the number of the variant that the enum takes.
> repr(X as u8)
> repr(x.X as fieldsX)

Therefore, I would expect the following code to work:

```rust
#[derive(BorshSerialize)]
enum MyEnum {
    A = 20,
}

assert_eq!(MyEnum::A as u8, 20);
assert_eq!(MyEnum::A.try_to_vec().unwrap(), vec![20]);
```

However, it fails:

```text
running 1 test
thread 'x' panicked at 'assertion failed: `(left == right)`
  left: `[0]`,
 right: `[20]`', src/lib.rs:10:5
```

It is serialized the same as if the discriminant were not specified:

```rust
#[derive(BorshSerialize)]
enum MyEnum2 {
    A,
}

assert_eq!(
    MyEnum2::A.try_to_vec().unwrap(),
    MyEnum::A.try_to_vec().unwrap(),
);
```

**Comment by frol** [comment]
@encody The specification denotes the type of the field, not the fact that `as u8` conversion will be used. That said, it might be worth considering adding this feature support. I am happy to review a PR if anyone will submit one.
