### ISSUE TITLE
Usage of syn::exports breaks the build

### ISSUE THREAD

**Issue by armaniferrante** [near/borsh-rs#2]
Recently `syn::export` was renamed to `syn::__private`, which breaks the build here. Users of borsh need to pin `syn` prior to `1.58`.  The breaking change: https://github.com/dtolnay/syn/commit/957840eba2c7f11c95e0227760d78dc481a91de7.

**Comment by frol** [comment]
@armaniferrante Thanks for bringing this up! I have merged a fix and now I am cutting a new release

**Comment by frol** [comment]
Borsh 0.8.0 is out with no_std support and the `syn::export` fixes. I am working on near-sdk-rs release.

**Comment by bowenwang1996** [comment]
> I am working on near-sdk-rs release.

@frol any update on near-sdk-rs release? It is currently blocking mocknet tests

**Comment by frol** [comment]
@bowenwang1996 Mike took the lead there: https://github.com/near/near-sdk-rs/pull/264
