### ISSUE TITLE
Restriction on Serializing Zero-Sized Types Affects Marker Component Usage

### ISSUE THREAD

**Issue by cybersoulK** [near/borsh-rs#259]
```rust
Err(Custom { kind: InvalidData, error: "Collections of zero-sized types are not allowed due to deny-of-service concerns on deserialization." })
```

The error detects a ECS component in my game (struct Dynamic) that works as a marker. i have many, and they are very useful components.

This change makes it unusable for me... :(

https://github.com/near/borsh-rs/blob/903601b26a1fc11ead79a62c45b77faeedf7e6a1/borsh/src/error.rs#L3

**Comment by cybersoulK** [comment]
ok looking at my serialization data again, it's not the empty hashmap,
It's the a ECS component in my game called Dynamic that works as a marker. i have many, and they are very useful.
This is a big restriction for me.

**Comment by dj8yfo** [comment]
@cybersoulK , we've decided that using zero-sized types as keys in `HashSet`/`HashMap` is impractical, as there cannot be more that one instance of the type (and, transitively, more than one key in collection of this type).

Please share a minimal excerpt from your code to illustrate how this case is useful for you.
 Ideally, if you shared it as a compilable repo with a previous version of `borsh`.

**Comment by cybersoulK** [comment]
yep, i cannot see any Hashmap Key, or Vec Value that is an empty struct. i looked 10 times at the data

**Comment by dj8yfo** [comment]
@cybersoulK , this is probably due to an optimization from compiler, where it makes single-variant enum zero-size. 
https://github.com/rust-lang/rust/issues/37649 . 
Can likely be helped with adding `#[repr(u8)]` attribute to the definition.

**Comment by cybersoulK** [comment]
Thank you ❤️, #[repr(u8)] should be good enough.
If there was anything can could be done is Borsh Derive to correct it automatically, would be nice.

**Comment by cybersoulK** [comment]
oh, congrats coming a long way with borsh 1.2!
