### ISSUE TITLE
Should `std` feature imply `rc` feature and vice-versa?

### ISSUE THREAD

**Issue by Fuuzetsu** [near/borsh-rs#266]
I'm not sure why these are separate. I think you can't enable `rc` without `std` and if you enable `std` then you also have `Rc` and `Arc` whether you like it or not.

Ideally `rc` would just get removed but enabling it as part of `std` seems like the second best thing.

**Comment by Fuuzetsu** [comment]
I guess serde also has `rc` feature, along with this comment:

```
# Opt into impls for Rc<T> and Arc<T>. Serializing and deserializing these types
# does not preserve identity and may result in multiple copies of the same data.
# Be sure that this is what you want before enabling this feature.
rc = []
```

**Comment by frol** [comment]
@Fuuzetsu `rc` is available from `alloc` crate, so std is not required to enable `rc`.

https://github.com/near/borsh-rs/blob/2b1f6c93f3087ab7c987b0654fae75a26bc67723/borsh/src/lib.rs#L139-L140

**Comment by frol** [comment]
Though, we may indeed enable `rc` feature for `std`. @dj8yfo What do you think?
