### ISSUE TITLE
noob: Serialize to specific array

### ISSUE THREAD

**Issue by FrankC01** [near/borsh-rs#28]
Early (rust, borsh, just about everything) learner.

Is it possible to provide the serialize a specific location to serialize into?

For example, if I have a 1 MB array and I would like to serialize to it after the 1024th byte.

Any help is appreciated.

**Comment by frol** [comment]
@FrankC01 Hey! You are welcome to rust, borsh, near learning!

All the structures implementing [BorshSerialize trait has `serialize` method](https://docs.rs/borsh/0.9.0/borsh/ser/trait.BorshSerialize.html#tymethod.serialize), which receives any writer to it. Thus, you can pass a vector or a slice into it. See the example in this PR #29

**Comment by FrankC01** [comment]
Looks good, I'll give it a whirl! Thanks
