### ISSUE TITLE
Build failure with v1.5.2:  item not found in `TypeParamBound`

### ISSUE THREAD

**Issue by nategraf** [near/borsh-rs#319]
Hi team, I use `borsh-derive` as a dependency in my project and got this build error this morning. I'll get some more information and try to get a smaller reproduction case.
```
    Compiling borsh-derive v1.5.2
error[E0599]: no variant or associated item named `PreciseCapture` found for enum `TypeParamBound` in the current scope
   --> /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/borsh-derive-1.5.2/src/internals/generics.rs:264:31
    |
264 |             | TypeParamBound::PreciseCapture(_) => {}
    |                               ^^^^^^^^^^^^^^ variant or associated item not found in `TypeParamBound`
```

**Comment by dj8yfo** [comment]
@nategraf well, a `cargo update` should help. 

it got an update in syn from https://docs.rs/syn/2.0.77/syn/enum.TypeParamBound.html to https://docs.rs/syn/2.0.87/syn/enum.TypeParamBound.html. 

it should not fail for --locked builds, as `borsh` version hasn't changed for those as well

but absolutely precisely and technically , yes, it's a omission/bug on `borsh`'s side, so we'll update the precise minimum 
required `syn` version https://github.com/near/borsh-rs/blob/master/borsh-derive/Cargo.toml#L28 and release that as 1.5.3

**Comment by nategraf** [comment]
Ah thank you. That is helpful. It looks like you `Cargo.toml` currently specifies `syn` with `version = "2"`. As far as I can tell, it looks like `PreciseCapture` was introduced with version `2.0.81`. With that, it would be good to specify this as the minimum version in your `Cargo.toml`. I've opened a PR to do so. No worries if this is not the right solution for you.

https://github.com/near/borsh-rs/pull/320
