### ISSUE TITLE
Borsh derive fails when using private types when derived on public type

### ISSUE THREAD

**Issue by austinabell** [near/borsh-rs#41]
Roughly, the pattern is:

```
#[derive(BorshSerialize, BorshDeserialize)]
struct Outer<T> {
    v: private::Inner<T>,
}

mod private {
    use super::*;

    #[derive(BorshSerialize, BorshDeserialize)]
    pub(crate) struct Inner<T> {
        val: T,
    }
}
```

And this fails because there is a where clause in the expanded which is unnecessary (`Inner<T>: BorshSerialize`) on the derive, which leaks the type for the bound on the trait.

https://github.com/austinabell/borsh-derive-repro/blob/main/src/lib.rs is a repro of this issue, and I've included Serde derive for this same case working.

**Comment by frol** [comment]
@austinabell It is not reproducible (thanks @dj8yfo for bringing this up), so I am closing this issue.
