### ISSUE TITLE
Please implement serialization and deserialization for [u8; 34]

### ISSUE THREAD

**Issue by karim-agha** [near/borsh-rs#42]
IPFS CIDv0 identifiers are 34 bytes long, and that's a common identifier that is stored on chain for off chain data.

If possible, please add an impl for `[u8;34]` for automatic derive-based BorshSerialize and BorshDeserialize. I'm not able to do this from an external crate.

**Comment by frol** [comment]
@karim-agha const generics MVP that we use in borsh is stabilized in [Rust 1.51 (release in March this year)](https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#const-generics-mvp), so you don't need nightly.

**Comment by frol** [comment]
I feel you might have misunderstood me. You just need to enable the feature in your Cargo.toml for `borsh` dependency.
