### ISSUE TITLE
Future proof schema API

### ISSUE THREAD

**Issue by matklad** [near/borsh-rs#46]
Currently this is a public type: 

```rust
#[derive(PartialEq, Debug, BorshSerialize, BorshDeserialize, BorshSchemaMacro)]
pub struct BorshSchemaContainer {
    /// Declaration of the type.
    pub declaration: Declaration,
    /// All definitions needed to deserialize the given type.
    pub definitions: HashMap<Declaration, Definition>,
}
```

This is ungreat -- all public fields make it impossible to make any kind of change to this structure. See #45 for example of the change we might want to do here (replacing HashMap with a BTreeMap to avoid hashbrown). 

We should make it possible to change the internal representation without breaking public API, but that itself would necessitate a semver break.

**Comment by dj8yfo** [comment]
current issue is great detail on #51 's sub-issue

**Comment by dj8yfo** [comment]
@frol this is a sample variant https://gist.github.com/dj8yfo/da468206a03feca6d08698cbfc868ea0

**Comment by dj8yfo** [comment]
@frol 
Taking into account container ser/de guarantee https://github.com/dj8yfo/borsh-rs/blob/tmp_link_container_guarantee/borsh/tests/test_schema_enums.rs#L164, 
the below link is a straightforward approach, which compiles, how this could be done, taking the above into account.

https://gist.github.com/dj8yfo/da468206a03feca6d08698cbfc868ea0

**Comment by frol** [comment]
@dj8yfo Do you mean canonicity enforcement (#160) when say "container ser/de guarantee"? Can you shed some light on why it matters here?

https://gist.github.com/dj8yfo/da468206a03feca6d08698cbfc868ea0#file-f_p_schema_api-rs-L139-L174 - This interface looks good to me (I would only ask not to shorten the names to "*_def", instead, use a full word `get_definition`)

**Comment by dj8yfo** [comment]
@frol No, i mean, that the container `BorshSchemaContainer` has some format of ser/de, which has been committed to in `insta` test.
It also has some `BorshSchema` implementation which is supposed to describe the format.

In gist i've removed derived implementations of `BorshSerialize`, `BorshDeserialize` for `BorshSchemaContainer`, as they depend on internal `BorshSchemaContainer` struct representation and replaced them with versions, that depend on declared public methods `declaration()` and `definitions()`, which are supposed to allow not changing the ser/de format, which has been committed to.

I missed to do the same for `impl BorshSchema for BorshSchemaContainer
` in the gist at first, updated it now.

**Comment by dj8yfo** [comment]
taking this issue
