### ISSUE TITLE
Update CI to run for branches

### ISSUE THREAD

**Issue by austinabell** [near/borsh-rs#60]
Would be ideal to just use github actions to keep it consistent, as well as travis having some issues semi-recently.

This needs to be run for PR branches because something simple like: https://github.com/near/borsh-rs/pull/47 can break compatibility.

**Comment by matklad** [comment]
being tackled by https://github.com/near/borsh-rs/pull/57 I belive.

**Comment by austinabell** [comment]
> being tackled by #57 I belive.

Oh, oops, I'm blind and missed seeing that PR
