### ISSUE TITLE
Failed to derive borsh ser/de in a recursive data structure

### ISSUE THREAD

**Issue by ailisp** [near/borsh-rs#7]
Minimal example:
```
#[derive(BorshSerialize, BorshDeserialize)]
enum A {
    X,
    Y(Box<A>),
}
```
gives compilation error:
```
error[E0275]: overflow evaluating the requirement `Box<A>: BorshSerialize`
 --> src/main.rs:3:10
  |
3 | #[derive(BorshSerialize, BorshDeserialize)]
  |          ^^^^^^^^^^^^^^
  |
```

**Comment by ailisp** [comment]
serde, can handle this case, btw

**Comment by vantessel** [comment]
Any plan to support this anytime soon?

**Comment by frol** [comment]
@vantessel I believe the original motivation died out and there is currently no champion to implement it. I am happy to review a PR if anyone is ready to contribute the implementation, just make sure you read the discussion in PR #96 that did not get through.
